#
# Copyright (C) Intel 2015
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

HOST_TESTS=host_tests.cpp
AOSP_TESTS=aosp_tests.cpp
function header
{
echo "/*" > $1
echo " * Copyright (C) Intel $(date +%Y)" >> $1
echo " *" >> $1
echo " * Licensed under the Apache License, Version 2.0 (the \"License\");" >> $1
echo " * you may not use this file except in compliance with the License." >> $1
echo " * You may obtain a copy of the License at" >> $1
echo " *" >> $1
echo " *      http://www.apache.org/licenses/LICENSE-2.0" >> $1
echo " *" >> $1
echo " * Unless required by applicable law or agreed to in writing, software" >> $1
echo " * distributed under the License is distributed on an \"AS IS\" BASIS," >> $1
echo " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied." >> $1
echo " * See the License for the specific language governing permissions and" >> $1
echo " * limitations under the License." >> $1
echo " */" >> $1
echo "" >> $1
echo "/* Generated by update_tests.sh" >> $1
echo " * run source update_tests.sh to update" >> $1
echo " */" >> $1
echo "" >> $1
}

header $HOST_TESTS
echo "#include <stdio.h>" >> $HOST_TESTS
echo "">> $HOST_TESTS
echo "#include \"tests.h\"" >> $HOST_TESTS
echo "">> $HOST_TESTS
echo "#define ASSERT_EQ(x, y) do {\\">> $HOST_TESTS
echo "  if ((x) != (y)) {\\">> $HOST_TESTS
echo "    printf(\"test failed \" #x \" != \" #y \"\\n\");\\">> $HOST_TESTS
echo "  } else { \\">> $HOST_TESTS
echo "    printf(\"test OK \" #x \" == \" #y \"\\n\");\\">> $HOST_TESTS
echo "  } } while (0)">> $HOST_TESTS
echo "">> $HOST_TESTS
echo "int main(int argc, char **argv) {">> $HOST_TESTS
cat tests.h | perl -lane 'print if s/int (test_([^_]+)_([^\(\);]+))\(\);/  \/\/ Run $1\n  ASSERT_EQ(0, $1());/g' >> $HOST_TESTS
echo "">> $HOST_TESTS
echo "  return 0;">> $HOST_TESTS
echo "}">> $HOST_TESTS



header $AOSP_TESTS
echo "#include <gtest/gtest.h>" >> $AOSP_TESTS
echo "#include \"tests.h\"" >> $AOSP_TESTS

cat tests.h | perl -lane 'print if s/int (test_([^_]+)_([^\(\);]+))\(\);/\nTEST($2, $3) {\n  ASSERT_EQ(0, $1());\n}/g' >>  $AOSP_TESTS
